version: "3"
services:
  app:
    build: .
    image: jasonblanchard/jawn-workspace-client
    expose:
      - '80'
    networks:
      - backend
    environment:
      DB_NAME: jawn_test
      MONGO_HOST: mongo
      PORT: '8081'
      LOG_LEVEL: 'DEBUG'
      APP_SECRET: "$$2a$$10$$HuxYWte8dvZJM9UHBMEFZO" # TODO: Centralize this
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.1
    networks:
      - backend
networks:
  backend:
