version: "3.7"
services:
  app:
    build: .
    image: jasonblanchard/jawn-workspace-client
    command:
      - /bin/bash
      - -c
      - |
        npm start --production
    environment:
      PORT: 8080
      LOG_LEVEL: 'DEBUG'
      APP_BASE_PATH: ""
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f app:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    container_name: jawn-workspace-client
    networks:
      - default
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image: jasonblanchard/jawn-workspace-client:test
    command:
      - /bin/bash
      - -c
      - |
        tail -f /dev/null
    environment:
      CYPRESS_BASE_URL: "http://app:8080"
    container_name: jawn-workspace-client-test
    networks:
      - default
networks:
  default:


