version: "3"
services:
  app:
    image: "jasonblanchard/jawn-app:${TAG}"
    ports:
        - "80:80"
    networks:
      - backend
    env_file:
      - ./ops/web-variables.env
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.50'
      replicas: 2
  mongo:
    image: mongo:3.7.1
    command: --auth
    networks:
      - backend
    volumes:
        - "dbdata:/data/db"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '0.50'
      placement:
        constraints:
          - node.labels.type == db
networks:
  backend:
volumes:
  dbdata:
