// TODO: Convert to rems

const colors = {
  black: '#333',
  grayLight: '#ececec',
  grayVeryLight: '#fff',
  grayMedium: '#717171',
  grayDark: '#bfbfbf',
  white: 'white',
  green: '#30dc37',
  yellow: '#d4d01f',
  blue: '#6da0d6',
  blueDark: '#2a77c7',
  blueLight: '#adccec',
  red: '#de5c45',
  redDark: '#a04b3c',
};

export default {
  backgroundDarkest: colors.black,
  backgroundDark: colors.grayLight,
  backgroundLightest: colors.white,
  borderDark: colors.grayDark,
  borderThin: '1px',
  borderRadiusSmall: '2px',
  colorSuccess: colors.green,
  colorWarning: colors.yellow,
  colorAccent: colors.blue,
  colorAccentBorder: colors.blueDark,
  colorAccentDisabled: colors.blueLight,
  colorDanger: colors.red,
  colorDangerBorder: colors.redDark,
  fontColorLightest: colors.grayMedium,
  fontColorDark: colors.black,
  fontFamily: 'Helvetica Neue, sans-serif',
  fontFamilyBrand: 'MoonLight, sans-serif',
  fontFamilyBrandHeading: 'MoonRegular, sans-serif',
  fontSizeLarge: '25px',
  fontSizeMedium: '14px',
  fontSizeSmall: '12px',
  letterSpacingBrand: '3px',
  textLightest: colors.grayVeryLight,
  spacingSmall: '2px',
  spacingMedium: '5px',
  colors,
};
